[project]
name = "pdfp"
version = "0.2.2"
description = "PDF Processor - a GUI for some common PDF operations."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gtts>=2.5.4",
    "ocrmypdf>=17.11.0",
    "pymupdf>=1.28.2",
    "pyside6>=6.11.2",
    "send2trash>=2.1.0",
]

[tool.uv]
package = true

[project.scripts]
pdfp = "pdfp.main:main"

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "mypy>=2.3.1",
    "ruff>=0.16.5",
]

[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "D",
    "missing-copyright-notice",
    "raw-string-in-exception",
    "raise-vanilla-args",
    "docstring-missing-returns",
    "missing-trailing-comma",
    "invalid-function-name",
    "too-many-public-methods",
    "error-instead-of-exception",
    "docstring-missing-exception",
]
